---
- name: test
  gather_facts: false
  hosts: 'hosts'
  vars:
    ansible_ssh_user: tarkov
  become: yes
 
  tasks:
    - name: Установка Nginx
      apt:
        name: nginx
        state: latest
      become: yes

    - name: Запуск Nginx
      service:
        name: nginx
        state: started
      become: yes
